'use strict';
let state, view='overview', selectedEmployee='director', detailId, stream, refreshTimer, toastTimer;
const $=(q,root=document)=>root.querySelector(q);
const $$=(q,root=document)=>[...root.querySelectorAll(q)];
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function employee(id){return state.employees.find(e=>e.id===id);}
function avatar(e,mini=false){return el('span',mini?'mini-avatar':`avatar avatar-${e.id}`,e.initials);}
function pill(status){return el('span',`pill ${status}`,{queued:'Queued',running:'Working',blocked:'Blocked',paused:'Needs attention',review:'For review',done:'Completed',cancelled:'Cancelled',ready:'Ready'}[status]||status);}
function button(text,cls,fn){const n=el('button',cls,text);n.type='button';n.addEventListener('click',fn);return n;}
function empty(title,copy,action){const n=el('div','empty');n.append(el('span','empty-symbol','◫'),el('h3','',title),el('p','',copy));if(action)n.append(button('Assign your first task ↗','secondary',action));return n;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,7000);}
async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Scout-Token':state.token},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');await refresh();return data;}
async function act(path,body){try{return await api(path,body);}catch(e){toast(e.message);return null;}}
function show(name,id){view=name;if(id)selectedEmployee=id;$$('.view').forEach(n=>n.hidden=n.id!==`view-${view}`);$$('nav button').forEach(n=>n.classList.toggle('active',n.dataset.view===view));$$('.employee-nav').forEach(n=>n.classList.toggle('active',view==='employee'&&n.dataset.employee===selectedEmployee));$('#breadcrumb').textContent=view==='employee'?employee(selectedEmployee).name:{overview:'Overview',team:'AI employees',tasks:'Task board',knowledge:'Company knowledge',activity:'Activity',flows:'Workflows',pipeline:'Leads & offers',projects:'Projects',library:'Deliverable library',reviews:'Review inbox',responsibilities:'Responsibilities',connections:'Tools & connections'}[view];if(view==='knowledge')renderKnowledge();render();window.scrollTo({top:0,behavior:'instant'});}
function openTask(id='director'){$('#assign-employee').value=id;$('#task-dialog').showModal();}
function renderEmployees(){for(const target of ['#overview-team','#team-grid']){const root=$(target);root.replaceChildren();state.employees.forEach(e=>{const n=el('article','employee-card'),top=el('div','card-top'),name=el('div');name.append(el('h3','',e.name),el('p','',e.role));top.append(avatar(e),name,pill(e.busy?'running':'ready'));const chips=el('div','chips');e.responsibilities.slice(0,2).forEach(r=>chips.append(el('span','chip',r)));const footer=el('div','card-footer'),tasks=state.tasks.filter(t=>t.employee_id===e.id);footer.append(el('span','',`${tasks.length} task${tasks.length!==1?'s':''} · ${e.session_id?'Session saved':'No session yet'}`),button('Open workspace ↗','',()=>show('employee',e.id)));n.append(top,el('p','description',e.description),chips,footer);root.append(n);});}const nav=$('#employee-nav');nav.replaceChildren();state.employees.forEach(e=>{const n=button('','employee-nav',()=>show('employee',e.id));n.dataset.employee=e.id;n.classList.toggle('active',view==='employee'&&e.id===selectedEmployee);const label=el('div','',e.name);label.append(el('small','',e.role));n.append(avatar(e,true),label,el('span',`status-dot ${e.busy?'working':''}`));nav.append(n);});}
function renderOverview(){const metrics=[['AI employees',state.employees.length,'Specialists ready for your brief','♙'],['Working now',state.tasks.filter(t=>t.status==='running').length,'Live tasks across your team','↗'],['Awaiting review',state.tasks.filter(t=>t.status==='review').length,'Deliverables ready for a decision','◫'],['Completed',state.tasks.filter(t=>t.status==='done').length,'Work you reviewed and closed','✓']];$('#metrics').replaceChildren(...metrics.map(([label,value,copy,icon])=>{const n=el('div','metric'),l=el('div','metric-label',label);l.append(el('span','metric-icon',icon));n.append(l,el('strong','',String(value)),el('small','',copy));return n;}));$('#recent-work').replaceChildren();const recent=[...state.tasks].reverse().slice(0,4);if(!recent.length)$('#recent-work').append(empty('Your team’s work starts here','Assign a goal to Atlas or a focused task to a specialist.',()=>openTask()));recent.forEach(t=>{const e=employee(t.employee_id),n=button('','recent-row',()=>openDetail(t.id)),content=el('div','row-content');content.append(el('strong','',t.title),el('small','',`${e.name} · ${e.role}`));n.append(avatar(e),content,pill(t.status),el('span','muted','↗'));$('#recent-work').append(n);});}
function resultLinks(task,root){const actions=el('div','message-actions');if(task.result){const a=el('a','','Download result ↓');a.href=`/api/result?task=${task.id}`;actions.append(a);}task.artifacts.forEach(a=>{const link=el('a','',`${a.name} ↓`);link.href=`/api/artifact?task=${task.id}&id=${encodeURIComponent(a.id)}`;actions.append(link);});root.append(actions);}
function renderResult(text,root){let leads;try{leads=JSON.parse(text);}catch(_){}if(Array.isArray(leads)&&leads.length&&leads.every(l=>l&&['Lead Name','Type of Lead','Reasoning and Evaluation','Conclusion & Recommendation'].every(k=>typeof l[k]==='string'))){leads.forEach(l=>{const n=el('article','lead-result');n.append(el('span','eyebrow',l['Type of Lead']),el('h3','',l['Lead Name']),el('h4','','Reasoning and evaluation'),el('p','',l['Reasoning and Evaluation']),el('h4','','Conclusion & recommendation'),el('p','recommendation',l['Conclusion & Recommendation']));root.append(n);});}else root.append(el('div','message-text',text));}
function renderEmployee(){const e=employee(selectedEmployee),heading=el('div','employee-heading'),label=el('div');label.append(el('h1','',e.name),el('p','',`${e.role} · ${e.department}`));const actions=el('div','heading-actions');actions.append(pill(e.busy?'running':'ready'),button('Configure employee','secondary',openConfig));heading.append(avatar(e),label,actions);$('#employee-heading').replaceChildren(heading);const history=$('#chat-history'),bottom=history.scrollHeight-history.scrollTop-history.clientHeight<100;history.replaceChildren();const tasks=state.tasks.filter(t=>t.employee_id===e.id);if(!tasks.length){const n=el('div','chat-empty');n.append(avatar(e),el('h2','',`Work with ${e.name}`),el('p','',e.description),el('p','','CrewBot’s context is already included. Start with a task below.'));history.append(n);}tasks.forEach(t=>{const group=el('div','message-group'),title=el('div','message-task');title.append(el('span','',t.title),button('View task ↗','text-button',()=>openDetail(t.id)));group.append(title);t.messages.forEach(m=>{const n=el('div',`message ${m.role}`);n.append(el('div','message-label',m.role==='user'?'YOU':e.name.toUpperCase()));if(m.role==='assistant')renderResult(m.text||(t.status==='running'?'Working on your task…':''),n);else n.append(el('div','message-text',m.text));group.append(n);});if(t.error)group.append(el('div','message-error',t.error));group.append(pill(t.status));resultLinks(t,group);history.append(group);});if(bottom)history.scrollTop=history.scrollHeight;$('#starters').replaceChildren();if(!tasks.length)e.starters.forEach(s=>$('#starters').append(button(`${s} ↗`,'starter',()=>{$('#chat-message').value=s;$('#chat-message').focus();})));const role=$('#role-panel');role.replaceChildren(el('h3','','What I handle'));const ul=el('ul');e.responsibilities.forEach(r=>ul.append(el('li','',r)));role.append(ul,el('span','eyebrow','AVAILABLE TOOLS'));['Live web research','Hosted Python & shell','Shared company context',...(e.id==='director'?['Specialist delegation']:[])].forEach(c=>role.append(el('span','chip',c),document.createTextNode(' ')));role.append(el('hr'),el('h3','','Persistent workspace'),el('span','eyebrow','AGENT ID'),el('code','',e.agent_id||'Created with the first task'),el('span','eyebrow','SESSION'),el('code','',e.session_id||'A hosted session starts with your first task'),el('span','eyebrow','MODEL'),el('code','',e.configuration.model),el('hr'),el('p','','Client messages remain drafts until you request sending through an available tool.'));}
function renderBoard(){const search=$('#task-search').value.toLowerCase(),role=$('#task-filter').value,tasks=state.tasks.filter(t=>(!role||t.employee_id===role)&&`${t.title} ${t.description}`.toLowerCase().includes(search));$('#board-count').textContent=`${tasks.length} task${tasks.length!==1?'s':''}`;$('#task-board').replaceChildren();[['Waiting',['queued','blocked','paused','cancelled']],['Working',['running']],['For review',['review']],['Completed',['done']]].forEach(([title,statuses])=>{const list=tasks.filter(t=>statuses.includes(t.status)),col=el('div','board-column'),h=el('div','column-heading',title);h.append(el('span','',String(list.length)));col.append(h);if(!list.length)col.append(el('div','board-empty',title==='Waiting'?'New tasks appear here':'Nothing here yet'));[...list].reverse().forEach(t=>{const e=employee(t.employee_id),n=button('','task-card',()=>openDetail(t.id)),foot=el('div','task-bottom');foot.append(avatar(e,true),el('span','',e.name),el('span','',t.priority==='high'?'↑ High priority':t.parent_id?'↳ Delegated':''));n.append(pill(t.status),el('strong','',t.title),el('p','',t.description),foot);col.append(n);});$('#task-board').append(col);});}
function renderKnowledge(){const form=$('#knowledge-form');form.replaceChildren();const labels={name:'Company name',positioning:'Positioning',summary:'Company summary',market:'Target market',services:'Core services',portfolio:'Portfolio',business_model:'Business model',goals:'Company goals',operating_rules:'Operating rules'};Object.entries(state.company).forEach(([key,value])=>{const l=el('label',['summary','goals','operating_rules'].includes(key)?'full-width':'',labels[key]||key),input=el(key==='name'||key==='positioning'?'input':'textarea');input.name=key;input.value=Array.isArray(value)?value.join('\n'):value;input.required=key==='name';if(input.tagName==='TEXTAREA')input.rows=key==='summary'?4:5;l.append(input);if(Array.isArray(value))l.append(el('small','','One item per line.'));form.append(l);});const actions=el('div','form-actions');actions.append(el('p','','Updates are included in every new task, including existing sessions.'));const b=el('button','primary','Save company knowledge');b.type='submit';actions.append(b);form.append(actions);}
function renderActivity(){$('#activity-list').replaceChildren();if(!state.activity.length)$('#activity-list').append(empty('A clear record of your team’s work','Events appear when you assign work or update the workspace.'));[...state.activity].reverse().slice(0,200).forEach(a=>{const row=el('div','activity-row');row.append(el('time','',new Date(a.time).toLocaleString()),el('div','activity-message',a.message));if(a.task_id)row.append(button(employee(a.employee_id).name+' ↗','',()=>openDetail(a.task_id)));$('#activity-list').append(row);});}
function openDetail(id){detailId=id;renderDetail();if(!$('#detail-dialog').open)$('#detail-dialog').showModal();}
function renderDetail(){if(!detailId)return;const t=state.tasks.find(t=>t.id===detailId);if(!t)return;const e=employee(t.employee_id);$('#detail-label').textContent=t.parent_id?'DELEGATED TASK':'ASSIGNED TASK';$('#detail-title').textContent=t.title;const root=$('#task-detail');root.replaceChildren();const meta=el('div','detail-meta');meta.append(pill(t.status),el('span','',`${e.name} · ${e.role}`),el('span','',new Date(t.created_at).toLocaleDateString()));root.append(meta,el('div','detail-brief',t.description));if(t.error)root.append(el('div','message-error',t.error));const text=t.result||t.messages.find(m=>m.role==='assistant')?.text;if(text){root.append(el('h3','','Deliverable'));const result=el('div','detail-result');renderResult(text,result);root.append(result);}else root.append(el('p','',t.status==='running'?'Your employee is working. Output and events will stream here.':'A deliverable will appear after this task runs.'));resultLinks(t,root);const children=state.tasks.filter(c=>c.parent_id===t.id);if(children.length){root.append(el('h3','','Specialist tasks'));children.forEach(c=>{const b=button(c.title,'child-task',()=>openDetail(c.id));b.append(pill(c.status));root.append(b);});}const actions=el('div','detail-actions');if(['blocked','paused','queued'].includes(t.status))actions.append(button(t.submitted?'Resume observation':'Run task ↗','primary',()=>taskAction(t.id,'run')));if(t.status==='review')actions.append(button('Reviewed — mark complete ✓','primary',()=>taskAction(t.id,'complete')));if(['queued','running','blocked','paused'].includes(t.status))actions.append(button('Stop task','secondary',()=>taskAction(t.id,'cancel')));if(t.parent_id)actions.append(button('View parent goal ↗','secondary',()=>openDetail(t.parent_id)));root.append(actions);}
async function taskAction(id,action){const r=await act('/api/task-action',{task_id:id,action});if(r&&action==='complete')toast('Task marked complete.');}
function openConfig(){const config=employee(selectedEmployee).configuration;['name','model','instructions'].forEach(k=>$('#config-form').elements[k].value=config[k]);$('#config-dialog').showModal();}
function render(){if(!state)return;$('#connection-status').textContent=state.credential_ready?'● API key configured':'○ API key needed';$('#connection-status').classList.toggle('ready',state.credential_ready);$('#task-count').textContent=String(state.tasks.filter(t=>!['done','cancelled'].includes(t.status)).length);$('#project-id').textContent=state.project_id;$('#connection-copy').textContent=state.credential_ready?'An API key is configured on this server. Your employees can start hosted sessions.':'The local workspace is ready. Add your replacement OpenAI API key to run employee tasks.';if(view==='overview'||view==='team')renderEmployees();if(view==='overview')renderOverview();if(view==='employee')renderEmployee();if(view==='tasks')renderBoard();if(view==='activity')renderActivity();if($('#detail-dialog').open)renderDetail();if(typeof renderOperations==='function')renderOperations();}
async function refresh(){const r=await fetch('/api/state');if(!r.ok)throw new Error('Workspace unavailable');state=await r.json();render();}
function scheduleRefresh(){if(!refreshTimer)refreshTimer=setTimeout(async()=>{refreshTimer=null;try{await refresh();}catch(e){toast(e.message);}},180);}
document.addEventListener('click',e=>{const n=e.target.closest('[data-view]');if(n&&state)show(n.dataset.view);const close=e.target.closest('.close-dialog');if(close)close.closest('dialog').close();});
$$('.new-task').forEach(b=>b.addEventListener('click',()=>openTask(view==='employee'?selectedEmployee:'director')));
for(const id of ['#connection-button','#connection-status'])$(id).addEventListener('click',()=>$('#connection-dialog').showModal());
$('#detail-dialog').addEventListener('close',()=>detailId=null);
$('#task-form').addEventListener('submit',async e=>{e.preventDefault();const b=$('button[type=submit]',e.target);b.disabled=true;const r=await act('/api/tasks',Object.fromEntries(new FormData(e.target)));b.disabled=false;if(r){$('#task-dialog').close();e.target.reset();show('tasks');openDetail(r.task_id);}});
$('#director-form').addEventListener('submit',async e=>{e.preventDefault();const text=$('#director-goal').value.trim();if(!text)return;const b=$('button',e.target);b.disabled=true;const r=await act('/api/tasks',{employee_id:'director',title:text.slice(0,100),description:text});b.disabled=false;if(r){$('#director-goal').value='';show('employee','director');}});
$('#chat-form').addEventListener('submit',async e=>{e.preventDefault();const text=$('#chat-message').value.trim();if(!text)return;const b=$('button',e.target);b.disabled=true;const r=await act('/api/tasks',{employee_id:selectedEmployee,title:text.slice(0,100),description:text});b.disabled=false;if(r)$('#chat-message').value='';});
$('#chat-message').addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();$('#chat-form').requestSubmit();}});
$('#fresh-session').addEventListener('click',async()=>{if(employee(selectedEmployee).busy)return toast('Wait for this employee to finish working.');if(!window.confirm('Start a fresh conversation? Previous task results and sessions are retained.'))return;const r=await act('/api/reset-session',{employee_id:selectedEmployee});if(r)toast('The next task will start a fresh hosted conversation.');});
$('#task-search').addEventListener('input',renderBoard);$('#task-filter').addEventListener('change',renderBoard);
$('#knowledge-form').addEventListener('submit',async e=>{e.preventDefault();const body={};for(const[key,value]of new FormData(e.target))body[key]=Array.isArray(state.company[key])?value.split('\n').map(v=>v.trim()).filter(Boolean):value.trim();const r=await act('/api/company',body);if(r)toast('Company knowledge saved for the whole team.');});
$('#config-form').addEventListener('submit',async e=>{e.preventDefault();const b=$('button[type=submit]',e.target);b.disabled=true;const r=await act('/api/configuration',{...Object.fromEntries(new FormData(e.target)),employee_id:selectedEmployee});b.disabled=false;if(r){$('#config-dialog').close();toast('Configuration saved. Start a fresh conversation to apply it.');}});
async function init(){try{await refresh();for(const id of ['#assign-employee','#task-filter'])state.employees.forEach(e=>{const o=el('option','',`${e.name} — ${e.role}`);o.value=e.id;$(id).append(o);});renderKnowledge();stream=new EventSource(`/api/events?after=${state.sequence}`);stream.onmessage=scheduleRefresh;stream.onopen=()=>$('#event-connection').textContent='● Live updates';stream.onerror=()=>$('#event-connection').textContent='Reconnecting…';}catch(e){toast(e.message+'. Start dashboard.ps1 and refresh.');}}
init();
